jdbc: 
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/wtozz-web?useUnicode:true&characterEncoding:UTF-8
  username: wtozz
  password: 123456
  connectionTimeout: 60000

log:
  dir: /home/logs/train_jdbc